### ISSUE TITLE
Authentication integrated with SUAP

### ISSUE THREAD

**Issue by felipemfp** [cades-ifrn/ifrn-messenger-server#2]
### Briefing

We should provide a way to the users authenticated themselves using the SUAP credentials.

1. The user will try to login with his SUAP credentials
2. The server will try to obtain the JWT using SUAP API
3. ~The server will persist the JWT in database~
4. The server will encode and sign a new JWT for the user
5. The mobile application should store the JWT ~and refresh it before expiration~
6. ~On refresh, the server will also try to update the first JWT using SUAP API~

We will be using the SUAP API only to obtain the user classes. So ~if 6 step fails,~ we could simply ask the user to login again when he/she wants to update his classes (e.g.: at the beginning of a new semester). 

### Tasks

- [x] Create a client to use SUAP API
- [x] Create mutation to obtain JWT
- [x] Create mutation to refresh JWT
- [x] Create query to current user
